# Generated by Django 4.1.1 on 2022-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_image_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pix',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/profile_photo'),
        ),
    ]
