# Generated by Django 4.1.1 on 2022-09-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_profile_pix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
