# Generated by Django 4.1 on 2022-08-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_is_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_member',
        ),
    ]
