# Generated by Django 4.1 on 2022-08-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={},
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
