# Generated by Django 4.1 on 2022-08-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userprofile_options_userprofile_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
