# Generated by Django 4.1 on 2022-08-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
    ]
