# Generated by Django 4.1.1 on 2022-09-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_admin_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
