# Generated by Django 4.1.1 on 2022-09-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='polls_option',
        ),
    ]
