# Generated by Django 4.1.1 on 2022-09-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventmember_unique_together_and_more'),
        ('notification', '0002_eventinvite_maybe_no_yes_remove_notification_maybe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='no',
            name='member',
        ),
        migrations.RemoveField(
            model_name='yes',
            name='member',
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.DeleteModel(
            name='Maybe',
        ),
        migrations.DeleteModel(
            name='No',
        ),
        migrations.DeleteModel(
            name='Yes',
        ),
    ]
