# Generated by Django 4.1.1 on 2022-09-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_notification_options_notification_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='notification_type',
            field=models.CharField(choices=[('like', 'like'), ('group_request', 'group_request'), ('invite', 'invite')], max_length=50, null=True),
        ),
    ]
