# Generated by Django 4.1.1 on 2022-09-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_date_created_like_date_liked_and_more'),
        ('notification', '0003_alter_notification_options_notification_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='response',
        ),
        migrations.AddField(
            model_name='notification',
            name='maybe',
            field=models.ManyToManyField(related_name='maybe_members', to='groups.member'),
        ),
        migrations.AddField(
            model_name='notification',
            name='no',
            field=models.ManyToManyField(related_name='no_members', to='groups.member'),
        ),
        migrations.AddField(
            model_name='notification',
            name='yes',
            field=models.ManyToManyField(related_name='yes_members', to='groups.member'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'like'), ('group_request', 'group_request'), ('invite', 'invite')], max_length=50, null=True),
        ),
    ]
