# Generated by Django 4.1.1 on 2022-09-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_eventmember_unique_together_and_more'),
        ('notification', '0003_remove_no_member_remove_yes_member_eventinvite_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
