# Generated by Django 4.1.1 on 2022-09-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_event_end_time_event_start_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
