# Generated by Django 4.1.1 on 2022-09-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Group Request', 'Group Request'), ('Event Invite', 'Event Invite')], max_length=50, null=True),
        ),
    ]
