# Generated by Django 4.1.1 on 2022-09-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmember',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmember',
            name='user',
        ),
    ]
