# Generated by Django 4.1.1 on 2022-09-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='date_created',
            new_name='date_liked',
        ),
        migrations.RemoveField(
            model_name='like',
            name='is_active',
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='comment_liked_by', through='groups.Like', to='groups.member'),
        ),
        migrations.AddField(
            model_name='like',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_group', to='groups.group'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='post_liked_by', through='groups.Like', to='groups.member'),
        ),
    ]
