# Generated by Django 4.1.1 on 2022-09-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_comment_member_remove_group_admins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
    ]
