# Generated by Django 4.1.1 on 2022-09-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_request_messgae_grouprequest_request_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
