# Generated by Django 4.1.1 on 2022-09-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replies',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_replies', to='groups.comment'),
        ),
    ]
