# Generated by Django 4.1.1 on 2022-09-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, null=True)),
                ('created_date', models.DateTimeField(
                    auto_now_add=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.member')),
                ('group', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='groups.member')),
                ('poll', models.ManyToManyField(to='poll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(
                    blank=True, max_length=200, null=True)),
                ('vote', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='poll.poll')),
            ],
        ),
    ]
