# Generated by Django 4.1.1 on 2022-09-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_alter_poll_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
