# Generated by Django 4.1.1 on 2022-09-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouprequest'),
        ('poll', '0003_poll_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.member')),
                ('poll', models.ManyToManyField(to='poll.poll')),
            ],
        ),
    ]
